### ISSUE TITLE
footer Github Access 整个区域需要能点击，链接到Github

### ISSUE THREAD

**Issue by chrisli30** [OAK-Foundation/quadratic-funding-webapp#19]
![CleanShot 2021-07-10 at 16 27 53](https://user-images.githubusercontent.com/2616844/125178657-d682aa00-e19b-11eb-8a40-ffbea4e8c905.png)

需要链接到 https://github.com/OAK-Foundation/quadratic-funding-webapp

**Comment by imstar15** [comment]
PR https://github.com/OAK-Foundation/quadratic-funding-webapp/pull/37
