### ISSUE TITLE
底部所有的社交媒体链接，需要使用跟OAK官网一样的链接，每个按钮都要测试点击到OAK的社交媒体

### ISSUE THREAD

**Issue by chrisli30** [OAK-Foundation/quadratic-funding-webapp#20]
https://www.dropbox.com/s/nbq1dzr175vx6fj/CleanShot%202021-07-10%20at%2016.30.00.png?dl=0

**Comment by imstar15** [comment]
PR https://github.com/OAK-Foundation/quadratic-funding-webapp/pull/38
